{
 "title": "Microsoft IIS overview",
 "tags": [ "microsoft-iis-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_iis_requests_total{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(windows_iis_requests_total{job=~\"$job\"}, instance)"
   },
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(windows_iis_requests_total{job=~\"$job\",instance=~\"$instance\"}, site)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The request rate split by HTTP Method for an IIS site",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(windows_iis_requests_total{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{site}} - {{method}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "description": "Requests that have resulted in errors for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "errors/sec" } },
   "targets": [
    {
     "expr": "rate(windows_iis_locked_errors_total{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{site}} - locked"
    },
    {
     "expr": "rate(windows_iis_not_found_errors_total{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{site}} - not found"
    }
   ]
  },
  {
   "title": "Blocked async I/O requests",
   "type": "timeseries",
   "description": "Number of async I/O requests that are currently queued for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(windows_iis_blocked_async_io_requests_total{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}[$__interval:])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Rejected async I/O requests",
   "type": "timeseries",
   "description": "Number of async I/O requests that have been rejected for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(windows_iis_rejected_async_io_requests_total{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}[$__interval:])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Traffic sent",
   "type": "timeseries",
   "description": "The traffic sent by an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_iis_sent_bytes_total{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Traffic received",
   "type": "timeseries",
   "description": "The traffic received by an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_iis_received_bytes_total{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Files sent",
   "type": "timeseries",
   "description": "The files sent by an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "files/s" } },
   "targets": [
    {
     "expr": "rate(windows_iis_files_sent_total{job=~\"$job\", instance=~\"$instance\",  site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Files received",
   "type": "timeseries",
   "description": "The files received by an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "files/s" } },
   "targets": [
    {
     "expr": "rate(windows_iis_files_received_total{job=~\"$job\", instance=~\"$instance\",  site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "timeseries",
   "description": "The number of current connections to an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "windows_iis_current_connections{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Attempted connections",
   "type": "timeseries",
   "description": "The number of attempted connections to an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(windows_iis_connection_attempts_all_instances_total{job=~\"$job\", instance=~\"$instance\", site=~\"$site\"}[$__interval:])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Access logs",
   "type": "logs",
   "description": "Recent access logs from access logs file for an IIS site.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{job=~\"$job\", site=~\"$site\"} |= ``"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "File cache hit ratio",
   "type": "timeseries",
   "description": "The current file cache hit ratio for an IIS server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(windows_iis_server_file_cache_hits_total{job=~\"$job\", instance=~\"$instance\"}[$__interval:]) / clamp_min(increase(windows_iis_server_file_cache_queries_total{job=~\"$job\", instance=~\"$instance\"}[$__interval:]),1) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "URI cache hit ratio",
   "type": "timeseries",
   "description": "The current URI cache hit ratio for an IIS server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (increase(windows_iis_server_uri_cache_hits_total{job=~\"$job\", instance=~\"$instance\"}[$__interval:]) / clamp_min(increase(windows_iis_server_uri_cache_queries_total{job=~\"$job\", instance=~\"$instance\"}[$__interval:]),1)) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Metadata cache hit ratio",
   "type": "timeseries",
   "description": "The current metadata cache hit ratio for an IIS server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(windows_iis_server_metadata_cache_hits_total{job=~\"$job\", instance=~\"$instance\"}[$__interval:]) / clamp_min(increase(windows_iis_server_metadata_cache_queries_total{job=~\"$job\", instance=~\"$instance\"}[$__interval:]),1) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Output cache hit ratio",
   "type": "timeseries",
   "description": "The current output cache hit ratio for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(windows_iis_server_output_cache_hits_total{job=~\"$job\", instance=~\"$instance\"}[$__interval:]) / clamp_min(increase(windows_iis_server_output_cache_queries_total{job=~\"$job\", instance=~\"$instance\"}[$__interval:]), 1) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  }
 ]
}