{
 "title": "Java service details [V2, WIP]",
 "tags": [
  "java",
  "otel-agent"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(target_info,environment)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "query_result(count (    process_start_time_seconds{environment=\"$namespace\"} or    jvm_class_count{environment=\"$namespace\"} or    label_replace (        process_start_time_seconds{namespace=\"$namespace\"}        , \"service_name\", \"$1\", \"service\", \"(.+)\"    )) by (service_name))"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "query_result(max (    jvm_info{namespace=\"$namespace\", service=\"$service\"}     or     label_replace(target_info{environment=\"$namespace\", job=\"$service\"}, \"container\", \"$1\", \"k8s_container_name\", \"(.+)\")    or     process_start_time_seconds{namespace=\"$namespace\", service=\"$service\"}) by (container))"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(target_info{job=\"$service\", environment=\"$namespace\"},k8s_deployment_name)"
    }
   },
   { "name": "Filters" },
   {
    "name": "hpa_metric_name",
    "label": "HPA Metric Name",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{namespace=\"$namespace\", horizontalpodautoscaler=\"$service\"},metric_name)"
    }
   },
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "query_result(label_replace(    max (target_info{job=\"$service\", environment=\"$namespace\"}) by (k8s_pod_name, container_image_tag),    \"service_instance_id\", \"$1\", \"k8s_pod_name\", \"(.*)\")or label_replace(    max (jvm_info{service=\"$service\", namespace=\"$namespace\"}) by (pod),     \"service_instance_id\", \"$1\", \"pod\", \"(.+)\")or label_replace( max(jvm_memory_max_bytes{service=\"$service\", namespace=\"$namespace\"}) by (pod), \"service_instance_id\", \"$1\", \"pod\", \"(.+)\"))"
    }
   },
   {
    "name": "slo",
    "label": "SLO",
    "query": {
     "query": "label_values(slo:sli_error:ratio_rate1h{sloth_service=\"$service\"},sloth_slo)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Instances Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n    max (target_info{job=\"$service\", environment=\"$namespace\"}) by (k8s_pod_name, container_image_tag),\n    \"service_instance_id\", \"$1\", \"k8s_pod_name\", \"(.*)\"\n)\n\nor \n\nlabel_replace(\n    max (jvm_info{service=\"$service\", namespace=\"$namespace\"}) by (pod), \n    \"service_instance_id\", \"$1\", \"pod\", \"(.+)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_count{job=\"$service\", environment=\"$namespace\"}\n\nor \n\nlabel_replace(\n    jvm_threads_live_threads{service=\"$service\", namespace=\"$namespace\"},\n    \"service_instance_id\", \"$1\", \"pod\", \"(.+)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_instance_id) (jvm_memory_used_bytes{job=\"$service\", jvm_memory_type=\"heap\", environment=\"$namespace\"})*100/sum by(service_instance_id) (jvm_memory_max_bytes{job=\"$service\", jvm_memory_type=\"heap\", environment=\"$namespace\"})\n\nor \n\nlabel_replace(\n    sum by(pod) (jvm_memory_used_bytes{service=\"$service\", area=\"heap\", namespace=\"$namespace\"})*100/sum by(pod) (jvm_memory_max_bytes{service=\"$service\", area=\"heap\", namespace=\"$namespace\"}),\n    \"service_instance_id\", \"$1\", \"pod\", \"(.+)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_instance_id) (increase(http_server_request_duration_sum{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval])) / sum by(service_instance_id) (increase(http_server_request_duration_count{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]))\n\nor \n\nlabel_replace(\n    sum by(pod) (increase(http_server_requests_seconds_sum{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval])) / sum by(pod) (increase(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval])),\n    \"service_instance_id\", \"$1\", \"pod\", \"(.+)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": " sum by(service_instance_id) (60 * rate(http_server_request_duration_count{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]))\n\n or \n\nlabel_replace(\n    sum by(pod) (60 * rate(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval])),\n    \"service_instance_id\", \"$1\", \"pod\", \"(.+)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - (label_replace(\n    max (process_start_time_seconds{job=\"$service\", namespace=\"$namespace\"}) by (pod),\n    \"service_instance_id\", \"$1\", \"pod\", \"(.+)\"\n)\n\nor\n\nmax (process_start_time_seconds{service_name=\"$service\", environment=\"$namespace\"}) by (service_instance_id)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    count by(k8s_pod_name, process_runtime_version) (\n        target_info{environment=\"$namespace\", job=\"$service\"}\n    ), \n    \"service_instance_id\", \"$1\", \"k8s_pod_name\", \"(.*)\"\n)\n\nor \n\nlabel_replace(\n    label_replace(\n        count by (pod, version) (jvm_info{namespace=\"$namespace\", service=\"$service\"}), \n        \"service_instance_id\", \"$1\", \"pod\", \"(.+)\"), \n    \"process_runtime_version\", \"$1\", \"version\", \"(.+)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service dashboards", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 } },
  { "title": "Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Throughput - Public",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "traefik_public_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$deployment\"}\n\nor \n\ntraefik_public_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$service\"}",
     "legendFormat": "RPM per pod"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$deployment\"}) * \n    sum(\n        traefik_public_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$deployment\"}\n    )\n\nor \n\nsum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$service\"}) * \n    sum(\n        traefik_public_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$service\"}\n    )",
     "legendFormat": "Total RPM"
    }
   ]
  },
  {
   "title": "Throughput - Internal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "traefik_internal_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$deployment\"}\n\nor \n\ntraefik_internal_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$service\"}",
     "legendFormat": "RPM per pod"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$deployment\"}) * \n    sum(\n        traefik_internal_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$deployment\"} \n    )\n\nor\n\nsum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$service\"}) * \n    sum(\n        traefik_internal_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$service\"} \n    )",
     "legendFormat": "Total RPM"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "avg (sum by(service_instance_id) (increase(http_server_request_duration_count{service_name=\"$service\", environment='$namespace'}[1m])))\n\nor \n\navg (sum by(pod) (increase(http_server_requests_seconds_count{service=\"$service\", env='$namespace'}[1m])))",
     "legendFormat": "RPM per pod"
    },
    {
     "expr": "sum (increase(http_server_request_duration_count{service_name=\"$service\", environment='$namespace'}[1m]))\n\nor \n\nsum (increase(http_server_requests_seconds_count{service=\"$service\", namespace='$namespace'}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request count per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (uri)(\n    label_replace(\n        increase(\n            http_server_request_duration_count{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]),\n        \"uri\", \"$1\", \"http_route\", \"(.+)\"\n    )\n)\n\nor \n\nsum by (uri) (increase(http_server_requests_seconds_count{service=\"$service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration, AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod)(\n    label_replace(\n        increase(\n            http_server_request_duration_sum{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]),\n        \"pod\", \"$1\", \"service_instance_id\", \"(.+)\"\n    )\n)\n\n/ sum by (pod)(\n    label_replace(\n        increase(\n            http_server_request_duration_count{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]),\n        \"pod\", \"$1\", \"service_instance_id\", \"(.+)\"\n    )\n)\n\nor \n\nsum by(pod) (increase(http_server_requests_seconds_sum{service=\"$service\"}[$__rate_interval])) / sum by(pod) (increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(http_server_request_duration_sum{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval])) / sum(increase(http_server_request_duration_count{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]))\n\nor \n\nsum(increase(http_server_requests_seconds_sum{service=\"$service\"}[$__rate_interval])) / sum(increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Average duration"
    }
   ]
  },
  {
   "title": "Request duration per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri)(\n    label_replace(\n        increase(\n            http_server_request_duration_sum{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]),\n        \"uri\", \"$1\", \"http_route\", \"(.+)\"\n    )\n)\n\n/ sum by (uri)(\n    label_replace(\n        increase(\n            http_server_request_duration_count{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]),\n        \"uri\", \"$1\", \"http_route\", \"(.+)\"\n    )\n)\n\nor \n\nsum by (uri)(increase(http_server_requests_seconds_sum{service=\"$service\"}[$__rate_interval])) / sum by (uri) (increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status)(\n    label_replace(\n        increase(\n            http_server_request_duration_count{service_name=\"$service\", environment=\"$namespace\"}[$__rate_interval]),\n        \"status\", \"$1\", \"http_response_status_code\", \"(.+)\"\n    )\n)\n\nor \n\nsum by (status)(increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "K8s & Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$deployment\"})\n\nor \n\nmax(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$service\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$deployment\"})\n\nor \n\nsum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=\"$deployment\"})\n\nor \n\nsum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=\"$service\"})",
     "legendFormat": "Unvailable"
    }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{container=\"$container\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pods|\"})",
     "legendFormat": "CPU limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{container=\"$container\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pods|\"})",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\", pod=~\"$pods|\"}[$__rate_interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max by(pod) (rate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\", pod=~\"$pods|\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HPA metric status for $hpa_metric_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "repeat": "hpa_metric_name",
   "targets": [
    {
     "expr": "label_replace(\n  max(kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"$service\",namespace=\"$namespace\",metric_name=\"$hpa_metric_name\", metric_target_type=\"utilization\"}) by (metric_name, metric_target_type),\n  \"metric_unit\", \n  \"Percent (0-100)\", \n  \"metric_target_type\", \n  \".*\"\n) or label_replace(\n  max(kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"$service\",namespace=\"$namespace\",metric_name=\"$hpa_metric_name\", metric_target_type!=\"utilization\"}) by (metric_name, metric_target_type),\n  \"metric_unit\", \n  \"Number\", \n  \"metric_target_type\", \n  \".+\"\n)",
     "legendFormat": "Target: {{metric_name}} {{metric_target_type}}"
    },
    {
     "expr": "max (kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"$service\",namespace=\"$namespace\", metric_name=\"$hpa_metric_name\"}) by (metric_name, metric_target_type)",
     "legendFormat": "Status: {{metric_name}} {{metric_target_type}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "JVM Heap per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(service_instance_id) (jvm_memory_used{environment=\"$namespace\", service_name=\"$service\", jvm_memory_type=\"heap\"})\n\nor \n\nsum by(pod) (jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", area=\"heap\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Minor GC Max  duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(service_instance_id) (increase(jvm_gc_duration_sum{environment=\"$namespace\", service_name=\"$service\", jvm_gc_name=\"G1 Young Generation\"}[1m]))\n\nor \n\nmax by(pod) (increase(jvm_gc_pause_seconds_sum{namespace=\"$namespace\", service=\"$service\", action=\"end of minor GC\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Non-heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(sum by(service_instance_id) (jvm_memory_used_bytes{environent=\"$namespace\", service_name=\"$service\", jvm_memory_type=\"non_heap\"}))\n\nor \n\navg(sum by(pod) (jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", area=\"nonheap\"}))",
     "legendFormat": "Average"
    },
    {
     "expr": "sum by(service_instance_id) (jvm_memory_used{environment=\"$namespace\", service_name=\"$service\", jvm_memory_type=\"non_heap\"})\n\nor \n\nsum by(pod) (jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", area=\"nonheap\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Full GC Max  duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(service_instance_id) (increase(jvm_gc_duration_sum{environment=\"$namespace\", service_name=\"$service\", jvm_gc_name=\"G1 Old Generation\"}[1m]))\n\nor \n\nmax by(pod) (increase(jvm_gc_pause_seconds_sum{namespace=\"$namespace\", service=\"$service\", action=\"end of major GC\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"POD\", container=\"$container\", image!=\"\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "GC events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(jvm_gc_action) (increase(jvm_gc_duration_count{environment=\"$namespace\", service_name=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SLO [WIP]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "SLO - $slo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "repeat": "slo",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - slo:sli_error:ratio_rate1h{\n    sloth_slo=\"$slo\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Experiment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Requests bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(traefik_service_requests_bytes_total{target_namespace=\"$namespace\", target_service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(traefik_service_responses_bytes_total{target_namespace=\"$namespace\", target_service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(client) (increase(traces_service_graph_request_total{server=\"$service\", server_environment=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream dependencies",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum by(server, connection_type) (rate(traces_service_graph_request_client_seconds_count{client=\"$service\", client_environment=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by ( server) (\n    rate(\n      traces_service_graph_request_client_seconds_sum{client=\"$service\", clien_environment=\"$namespace\"}              \n      [$__rate_interval]) / rate (traces_service_graph_request_client_seconds_count{client=\"$service\", client_environment=\"$namespace\"}               \n      [$__rate_interval]\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(server) (rate(traces_service_graph_request_failed_total{client=\"$service\", client_environment=\"$namespace\"}[$__rate_interval])) / sum by(server) (rate(traces_service_graph_request_total{client=\"$service\", client_environment=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(server, connection_type) (increase(traces_service_graph_request_total{client=\"$service\", client_environment=\"$namespace\"}[1m]))",
     "legendFormat": "{{server}} ({{connection_type}})"
    }
   ]
  },
  {
   "title": "HTTP Client requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(server_address) (increase(http_client_request_duration_count{service_name=\"$service\", environment=\"$namespace\"}[1m]))\n\nor \n\nsum by(client_name) (increase(http_client_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(error_type, server_address) (increase(http_client_request_duration_count{service_name=\"$service\", http_response_status_code!~\"1.*|2.*|3.*\", environment=\"$namespace\"}[1m]))\n\nor \n\nsum by(status, client_name) (increase(http_client_requests_seconds_count{service=\"$service\", outcome!=\"SUCCESS\", namespace=\"$namespace\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}