{
 "title": ".NET service details [WIP]",
 "tags": [ "dotnet" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{telemetry_sdk_language=\"dotnet\"},env)"
    }
   },
   { "name": "brand", "label": "Brand", "query": "PS, TR" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{env=\"$env\", legacy_brand=\"$brand\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick facts [WIP]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Service instances overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by(service_instance_id) (increase(http_server_request_duration_seconds_count{telemetry_sdk_language=\"dotnet\", env=\"$env\", legacy_brand=\"$brand\", service_name=\"$service\"}[5m])) / 5",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service_instance_id) (increase(http_server_request_duration_seconds_count{telemetry_sdk_language=\"dotnet\", env=\"$env\", legacy_brand=\"$brand\", service_name=\"$service\", http_response_status_code=~\"5..\"}[5m]))\n/\nsum by(service_instance_id) (increase(http_server_request_duration_seconds_count{telemetry_sdk_language=\"dotnet\", env=\"$env\", legacy_brand=\"$brand\", service_name=\"$service\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(service_instance_id, le) (rate(http_server_request_duration_seconds_bucket{service_name=\"$service\", env=\"$env\", legacy_brand=\"$brand\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum (increase(http_server_request_duration_seconds_count{telemetry_sdk_language=\"dotnet\", env=\"$env\", legacy_brand=\"$brand\", service_name=\"$service\"}[5m])) / 5",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(http_server_request_duration_seconds_count{telemetry_sdk_language=\"dotnet\", env=\"$env\", legacy_brand=\"$brand\", service_name=\"$service\", http_response_status_code=~\"5..\"}[5m]))\n/\nsum by(service_name) (increase(http_server_request_duration_seconds_count{telemetry_sdk_language=\"dotnet\", env=\"$env\", legacy_brand=\"$brand\", service_name=\"$service\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_server_request_duration_seconds_bucket{service_name=\"$service\", env=\"$env\", legacy_brand=\"$brand\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{service_name=\"$service\", env=\"$env\", legacy_brand=\"$brand\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_request_duration_seconds_bucket{service_name=\"$service\", env=\"$env\", legacy_brand=\"$brand\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Error logs stream",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{service_name=\"$service\"} |= `` | label_format level=detected_level | legacy_brand = \"$brand\" | level = `error`"
    }
   ]
  },
  { "title": "Kestrel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Queued connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(service_instance_id) (kestrel_queued_connections{env=\"$env\",service_name=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum by(service_instance_id) (kestrel_active_connections{env=\"$env\",service_name=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration, avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(service_instance_id) (increase(kestrel_connection_duration_seconds_sum{env=\"$env\", service_name=\"$service\"}[5m]))\n/\nsum by(service_instance_id) (increase(kestrel_connection_duration_seconds_count{env=\"$env\", service_name=\"$service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}