{
 "title": "PS-Handlers - PMS Integrations",
 "panels": [
  {
   "title": "PMS Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(IntegrationType, LogType) (count_over_time({service_name=\"PS-Handlers\"} | json | IntegrationType = `PMS` | LogType = `ERROR` [5m]))"
    }
   ]
  },
  {
   "title": "PMS Warn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count by(IntegrationType, LogType) (count_over_time({service_name=\"PS-Handlers\"} | json | IntegrationType = `PMS` | LogType = `WARN` [5m]))"
    }
   ]
  },
  {
   "title": "PMS Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count by(IntegrationType, LogType) (count_over_time({service_name=\"PS-Handlers\"} | json | IntegrationType = `PMS` | LogType = `INFO` [5m]))"
    }
   ]
  },
  {
   "title": "PMS Log Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by(IntegrationType, LogType) (count_over_time({service_name=\"PS-Handlers\"} | json | IntegrationType = `PMS` [5m]))"
    }
   ]
  }
 ]
}