{
 "title": "Events Service - investigation",
 "tags": [ "events-service" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "atmosphereStatus",
    "query": "broadcast, skip, error, acknowledged"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(events_service_onstatechange_total,service_instance_id)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": "int0, stag" }
  ]
 },
 "panels": [
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"events-service\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"events-service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=\"$deployment\"})\n\nor \n\nsum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=\"$service\"})",
     "legendFormat": "Unvailable"
    }
   ]
  },
  {
   "title": "Event delivery count rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(service_instance_id) (rate(events_service_event_delivery_count_hotels_total{environment=\"$namespace\", service_instance_id=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event delivery avg duration by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(service_instance_id) (rate(events_service_event_delivery_duration_hotels_seconds_sum{environment=\"$namespace\",service_instance_id=~\"$instance\"}[$__rate_interval])) / sum by(service_instance_id) (rate(events_service_event_delivery_duration_hotels_seconds_count{environment=\"$namespace\",service_instance_id=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event delivery count rate by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(type) (rate(events_service_event_delivery_count_types_total{environment=\"$namespace\",service_instance_id=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active hotels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count (sum by(hotel_id) (rate(events_service_event_delivery_count_hotels_total{environment=\"$namespace\", service_instance_id=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "onStateChange count by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(events_service_onstatechange_total{environment=\"$namespace\",service_instance_id=~\"$instance\"}) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "messageBroadcast count by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(events_service_message_broadcast_total{environment=\"$namespace\",service_instance_id=~\"$instance\"}) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "onStateChange count by result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(status) (rate(events_service_onstatechange_total{environment=\"$namespace\",service_instance_id=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "messageBroadcast rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(service_instance_id) (rate(events_service_message_broadcast_total{environment=\"$namespace\",service_instance_id=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "onStateChange $atmosphereStatus count by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "repeat": "atmosphereStatus",
   "targets": [
    {
     "expr": "sum by(service_instance_id) (rate(events_service_onstatechange_total{environment=\"$namespace\", status=\"$atmosphereStatus\",service_instance_id=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod restarts with reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{container=\"events-service\", namespace=\"$namespace\"}) by (reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spans by name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(traces_spanmetrics_calls_total{service=\"events-service\"}) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}