{
 "title": "Jobs Service",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Count Over Time by Customers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, sum by(customer) (count_over_time({service_name=~\"actabl\\\\.bi\\\\.datasetcopyservice|actabl\\\\.bi\\\\.jobs|actabl\\\\.bi\\\\.nightauditservice|actabl\\\\.bi\\\\.profitsageservice\"} | customer != `` [5m])))",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Count Over Time by Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, count by(job) (count_over_time(actabl_bi_job_process_total[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mass Transit Information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(messaging_masstransit_consumer_type) (messaging_masstransit_consume_active_ea_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum By Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(operation) (delta(actabl_bi_job_process_total{legacy_brand=\"PS\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Error by Service Name (Severity > 12)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(3, count by(service_name) (count_over_time({service_name=~\"actabl\\\\.bi\\\\.datasetcopyservice|actabl\\\\.bi\\\\.jobs|actabl\\\\.bi\\\\.nightauditservice|actabl\\\\.bi\\\\.profitsageservice\"} | severity_number > 12 [1m])))",
     "legendFormat": "{{scope_name}}"
    }
   ]
  },
  {
   "title": "Error by Service Name (Severity > 12)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(3, sum by(service_name) (rate({service_name=~\"actabl\\\\.bi\\\\.datasetcopyservice|actabl\\\\.bi\\\\.jobs|actabl\\\\.bi\\\\.nightauditservice|actabl\\\\.bi\\\\.profitsageservice\"} | severity_number > 12 [10m])))",
     "legendFormat": "{{scope_name}}"
    }
   ]
  },
  {
   "title": "Client Request Time In Queue by Job",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(5, sum by(le) (increase(http_client_request_time_in_queue_seconds_bucket{service_name=~\"actabl.bi.datasetcopyservice|actabl.bi.jobs|actabl.bi.nightauditservice|actabl.bi.profitsageservice\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Request Duration By Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, rate(http_client_request_duration_seconds_sum{job=~\"actabl.bi.datasetcopyservice|actabl.bi.jobs|actabl.bi.nightauditservice|actabl.bi.profitsageservice\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Request Duration By Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, rate(http_server_request_duration_seconds_sum{job=~\"actabl.bi.datasetcopyservice|actabl.bi.jobs|actabl.bi.nightauditservice|actabl.bi.profitsageservice\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}