{
 "title": "Jobs Service Drilldown",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customers",
    "label": "customers",
    "query": {
     "query": "label_values(actabl_bi_job_process_total,customer)"
    }
   },
   {
    "name": "jobs",
    "label": "jobs",
    "query": {
     "query": "label_values(actabl_bi_job_process_total,job)"
    }
   },
   {
    "name": "types",
    "label": "job types",
    "query": {
     "query": "label_values(messaging_masstransit_consume_active_ea_total,messaging_masstransit_consumer_type)"
    }
   },
   { "name": "environment", "label": "env", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  {
   "title": "Count Over Time Jobs by Customer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, count by(job) (count_over_time(actabl_bi_job_process_total{customer=\"$customers\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Over Time (Customers) by Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, sum by(service_name) (count_over_time({service_name=\"$jobs\"} | customer = `$customers` [5m])))",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Mass Transit Information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(messaging_masstransit_consumer_type) (messaging_masstransit_consume_active_ea_total{service_name=\"$jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum By Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(operation) (delta(actabl_bi_job_process_total{legacy_brand=\"PS\", service_name=\"$jobs\", customer=\"$customers\"}[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Error by Service Name (Severity > 12)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(3, count by(service_name) (count_over_time({service_name=\"$jobs\"} | severity_number > 12 [1m])))",
     "legendFormat": "{{scope_name}}"
    }
   ]
  },
  {
   "title": "Error by Service Name (Severity > 12)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(3, sum by(service_name) (rate({service_name=\"$jobs\"} | severity_number > 12 | service_name = `$jobs` [10m])))",
     "legendFormat": "{{scope_name}}"
    }
   ]
  },
  {
   "title": "Client Request Time In Queue by Job",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(5, sum by(le) (increase(http_client_request_time_in_queue_seconds_bucket{service_name=\"$jobs\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Request Duration By Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, rate(http_client_request_duration_seconds_sum{job=\"$jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Request Duration By Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, rate(http_server_request_duration_seconds_sum{job=\"$jobs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}