{
 "title": "Throughput + Resources + HPA",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "int0" },
   {
    "name": "service",
    "label": "Service",
    "query": "auth,alice-staff-backend,permissions-service,users-service,hotels-service,tickets-service,credit-cards-service,transcendent-gateway,events-service,alice-web"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_info{service=\"$service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_live_threads{service=\"$service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod) (jvm_memory_used_bytes{service=\"$service\", area=\"heap\"})*100/sum by(pod) (jvm_memory_max_bytes{service=\"$service\", area=\"heap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod) (increase(http_server_requests_seconds_sum{service=\"$service\"}[$__rate_interval])) / sum by(pod) (increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": " sum by(pod) (rate(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_uptime_seconds{service=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput on pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "avg (sum by(instance) (increase(http_server_requests_seconds_count{service=\"$service\", namespace='$namespace'}[1m])))",
     "legendFormat": "RPM per pod"
    },
    {
     "expr": "sum (increase(http_server_requests_seconds_count{service=\"$service\", namespace='$namespace'}[1m]))",
     "legendFormat": "Total RPM"
    }
   ]
  },
  {
   "title": "Request duration on pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(http_server_requests_seconds_sum{service=\"$service\"}[$__rate_interval])) / sum by(pod) (increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{service=\"$service\"}[$__rate_interval])) / sum(increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Average duration"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$service\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=\"$service\"})",
     "legendFormat": "Unvailable"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (increase(jvm_gc_pause_seconds_sum{namespace=\"$namespace\", container=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU usage & HPA CPU Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{container=\"$service\", resource=\"cpu\"})",
     "legendFormat": "CPU limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{container=\"$service\", resource=\"cpu\"})",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"$service\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"$service\", metric_target_type=\"utilization\", metric_name=\"cpu\"})*max(kube_pod_container_resource_requests{container=\"$service\", resource=\"cpu\"})/100",
     "legendFormat": "HPA target"
    },
    {
     "expr": "max by(pod) (rate(container_cpu_usage_seconds_total{container=\"$service\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap per pod + Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$service\"}) * 100) / avg(jvm_memory_max_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "(avg by(pod) (jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$service\"}) * 100) / avg by(pod) (jvm_memory_max_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request duration per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri)(increase(http_server_requests_seconds_sum{service=\"$service\"}[$__rate_interval])) / sum by (uri) (increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_server_requests_seconds_count{application='$service',namespace='$namespace'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput on ingress (public)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "traefik_public_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$service\"}",
     "legendFormat": "RPM per pod"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$service\"}) * \n    sum(\n        traefik_public_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$service\"}\n    )",
     "legendFormat": "Total RPM"
    }
   ]
  },
  {
   "title": "Throughput on ingress (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "traefik_internal_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$service\"}",
     "legendFormat": "RPM per pod"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_ready{namespace=\"$namespace\", deployment=\"$service\"}) * \n    sum(\n        traefik_internal_service_rpm:per_target{target_namespace=\"$namespace\", target_service=\"$service\"} \n    )",
     "legendFormat": "Total RPM"
    }
   ]
  }
 ]
}