{
 "title": "Tickets-service ES thread pool",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(process_uptime_seconds,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "500 ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "role:\"tickets-service\" AND environment:\"$env\" AND priority:\"ERROR\" AND message:\"500\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ES Queue Available Places",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (executor_queue_remaining_tasks{service=\"tickets-service\", env=\"$env\", name=\"esTaskExecutor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ES Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (executor_queued_tasks{service=\"tickets-service\", env=\"$env\", name=\"esTaskExecutor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ES Active (Busy) threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod) (executor_active_threads{service=\"tickets-service\", env=\"$env\", name=\"esTaskExecutor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ES Completed Tasks Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod) (executor_completed_tasks_total{service=\"tickets-service\", env=\"$env\", name=\"esTaskExecutor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ES Completed Tasks RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(executor_completed_tasks_total{service=\"tickets-service\", env=\"$env\", name=\"esTaskExecutor\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ES Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "avg(executor_pool_max_threads{service=\"tickets-service\", name=\"esTaskExecutor\", env=\"$env\"})",
     "legendFormat": "Max Size"
    },
    {
     "expr": "avg(executor_pool_core_threads{service=\"tickets-service\", name=\"esTaskExecutor\", env=\"$env\"})",
     "legendFormat": "Core Size"
    },
    {
     "expr": "avg(executor_pool_size_threads{service=\"tickets-service\", name=\"esTaskExecutor\", env=\"$env\"})",
     "legendFormat": "Actual Size"
    }
   ]
  }
 ]
}