{
 "title": "TRGW webhooks",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(process_uptime_seconds,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Received webhooks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(alice_webhooks_received_total{namespace=\"$env\"})",
     "legendFormat": "Received webhooks"
    }
   ]
  },
  {
   "title": "Delivery attempts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(webhook_delivery_attempts_total{namespace=\"$env\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivery attempts (SUM)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (webhook_delivery_attempts_total{namespace=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook delivery job duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(job_execution_duration_seconds_sum{namespace=\"$env\", name=\"process-alice-webhooks-job\"}[$__rate_interval])) / sum(rate(job_execution_duration_seconds_count{namespace=\"$env\", name=\"process-alice-webhooks-job\"}[$__rate_interval]))",
     "legendFormat": "Avg job duration"
    }
   ]
  },
  {
   "title": "Webhook cleanup job duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(job_execution_duration_seconds_sum{namespace=\"$env\", name=\"delete-all-successful-alice-webhooks-job\"}[$__rate_interval])) / sum(rate(job_execution_duration_seconds_count{namespace=\"$env\", name=\"delete-all-successful-alice-webhooks-job\"}[$__rate_interval]))",
     "legendFormat": "Avg job duration"
    }
   ]
  },
  {
   "title": "Delivery duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(webhook_delivery_duration_seconds_sum{namespace=\"$env\"}[$__rate_interval])) / sum(rate(webhook_delivery_duration_seconds_count{namespace=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Avg delivery duration"
    }
   ]
  }
 ]
}