{
 "title": "ALICE Monolith - JGroups",
 "tags": [
  "alice",
  "monolith",
  "jgroups"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "zone", "label": "Zone", "query": "prod,ent1" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jmx_scrape_duration_seconds,pod)"
    }
   },
   { "name": "jvm_memory_area", "query": "heap, nonheap" },
   {
    "name": "jvm_memory_pool",
    "query": "G1 Eden Space,G1 Survivor Space,G1 Old Gen"
   },
   {
    "name": "gc_type",
    "query": {
     "query": "label_values(java_lang_garbagecollector_collectioncount,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"alice-web\", namespace=\"$zone\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"alice-web\", namespace=\"prod\"}",
     "legendFormat": "Up & Running"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=\"alice-web\", namespace=\"prod\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "JVM Memory - ${pod}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "pod" },
  {
   "title": "JVM Memory - ${jvm_memory_area}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "repeat": "jvm_memory_area",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{pod=\"$pod\", namespace=\"$zone\", area=\"$jvm_memory_area\"}",
     "legendFormat": "{{pod}} - used"
    },
    {
     "expr": "jvm_memory_bytes_committed{pod=~\"$pod\", namespace=\"$zone\", area=\"$jvm_memory_area\"}",
     "legendFormat": "{{pod}} - committed"
    }
   ]
  },
  {
   "title": "JVM Memory Pool - ${jvm_memory_pool}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "jvm_memory_pool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pod=~\"$pod\", namespace=\"$zone\", pool=\"$jvm_memory_pool\"}",
     "legendFormat": "{{pod}} - used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pod=~\"$pod\", namespace=\"$zone\", pool=\"$jvm_memory_pool\"}",
     "legendFormat": "{{pod}} - committed"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 455 } },
  {
   "title": "${gc_type} - Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 456 },
   "repeat": "gc_type",
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(java_lang_garbagecollector_collectioncount{namespace=\"$zone\", pod=~\"$pod\", name=~\"$gc_type\"}[$__rate_interval]) * 60",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 466 } },
  {
   "title": "API - JMX scraping overhead",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 467 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, jmx_scrape_duration_seconds{namespace=\"$zone\", service=~\"alice-web*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.95, jmx_scrape_duration_seconds{namespace=\"$zone\", service=~\"alice-web*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API - JGroups xmit_table size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 467 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jgroupsreplication_protocol_size_of_all_messages_incl_headers{namespace=\"$zone\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API - JGroups num_suspected_members",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 467 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jgroupsreplication_protocol_num_suspected_members{namespace=\"$zone\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API - JGroups channel_sent_bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 476 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(jgroupsreplication_channel_sent_bytes{namespace=\"$zone\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API - JGroups channel_sent_messages ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 476 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(jgroupsreplication_channel_sent_messages{namespace=\"$zone\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API - JGroups channel_received_bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 486 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(jgroupsreplication_channel_received_bytes{namespace=\"$zone\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API - JGroups channel_received_messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 486 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(jgroupsreplication_channel_received_messages{namespace=\"$zone\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 496 },
   "collapsed": true,
   "panels": [
    {
     "title": "WRITER DB CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "${zone}-aliceapp-57", "Role": "WRITER" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "READER DB CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "${zone}-aliceapp-57", "Role": "READER" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Database connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dimensions": { "DBClusterIdentifier": "${zone}-aliceapp-57", "Role": "WRITER" },
       "metricName": "DatabaseConnections",
       "namespace": "AWS/RDS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Experiments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 497 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability @ AWS ALB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expression": "1 - ($FAILED_TARGET + $FAILED_ELB) / $TOTAL",
       "type": "math"
      }
     ]
    },
    {
     "title": "Row was updated or deleted by another transaction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 105 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:prod AND \"Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.alice.HotelUser#\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "com.mysql.jdbc.exceptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 105 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:prod AND priority:ERROR AND (role:\"web\" OR role:\"jobs\") AND message:com.mysql.jdbc.exceptions.*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Throughput @ K8s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{exported_service=\"${zone}-alice-web-http@kubernetes\"}[1m])) / 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency @ K8s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_request_duration_seconds_sum{exported_service=\"prod-alice-web-http@kubernetes\"}[$__rate_interval])) /\r\nsum(increase(traefik_service_request_duration_seconds_count{exported_service=\"prod-alice-web-http@kubernetes\"}[$__rate_interval]))",
       "legendFormat": "__auto",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "org.hibernate.exception",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 113 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:prod AND priority:ERROR AND (role:\"web\" OR role:\"jobs\") AND message:org.hibernate.exception.*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "GC Throughput PROD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "min by(job)(100 - (sum by (job, instance)(increase(jvm_gc_collection_seconds_sum[1m])) * 100 / sum by (job, instance) (increase(process_cpu_seconds_total[1m]))))"
      }
     ]
    },
    {
     "title": "G1 Old Generation PROD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 121 },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{container=\"aliceapp\", gc=\"G1 Old Generation\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC count PROD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "max (rate(jvm_gc_collection_seconds_count[1m])) by (job, gc)",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}