{
 "title": "ALICE Monolith - Jobs",
 "tags": [
  "alice",
  "monolith",
  "overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "zone", "label": "Zone", "query": "prod,ent1" }
  ]
 },
 "panels": [
  { "title": "Quick facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (kube_deployment_status_replicas_ready{deployment=\"alice-jobs\", namespace=\"$zone\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment) (kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"alice-jobs\", namespace=\"$zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB CPU %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "${zone}-aliceapp-57", "Role": "WRITER" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB-Reader CPU %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "${zone}-aliceapp-57", "Role": "READER" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Potential problems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    { "title": "Deep dive", "type": "dashlist", "gridPos": { "h": 16, "w": 8, "x": 0, "y": 7 } },
    {
     "title": "Ingress 404 issue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "role",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:${zone} AND (role:\"alice-staff-backend\") AND (message:\"404 Not Found\" AND message:\"prod-web-internal.aliceapp.com\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Elastic Search Result Window Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "role",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:${zone} AND (role:web OR role:jobs) AND message:\"Result Window\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Error initializing Grails",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "role",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:${zone} AND (role:\"web\" OR role:\"jobs\") AND message:\"Error initializing Grails\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Invalidating cached JSON for Hotel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "role",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:${zone} AND (role:\"web\" OR role:\"jobs\") AND message:\"Invalidating cached JSON for Hotel\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "JGroups DB Issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "\"java.sql.SQLException: Access denied for user\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Too many connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND priority:ERROR AND role:\"jobs\" AND message:\"Too many connections\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DB Connection Pool exhausted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:\"jobs\" AND priority:ERROR AND  message:\"org.apache.tomcat.jdbc.pool.PoolExhaustedException\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Lock wait timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:\"jobs\" AND message:\"com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "priority",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:jobs",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "prod_guest_sms_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "queue": "${zone}_guest_sms" },
     "metricName": "${zone}_guest_sms_count",
     "namespace": "ironmq",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "prod_guest_sms_count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Logs, WARN+ERROR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "priority",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:jobs AND (priority:ERROR OR priority:WARN)",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Elastic Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "zone" },
  {
   "title": "ES Search Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
     "metricName": "SearchRate",
     "namespace": "AWS/ES",
     "period": "10",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
      "select": {
       "name": "MIN",
       "parameters": [
        { "name": "SearchRate", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ES Indexing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
     "metricName": "IndexingRate",
     "namespace": "AWS/ES",
     "period": "10",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
      "select": {
       "name": "MIN",
       "parameters": [
        { "name": "SearchRate", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ES CPU Utilization (Master)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
     "metricName": "MasterCPUUtilization",
     "namespace": "AWS/ES",
     "period": "10",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
      "select": {
       "name": "MIN",
       "parameters": [
        { "name": "SearchRate", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "ES CPU Utilization (Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "period": "10",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
      "select": {
       "name": "MIN",
       "parameters": [
        { "name": "SearchRate", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "WRITER DB CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "${zone}-aliceapp-57", "Role": "WRITER" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "READER DB CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "${zone}-aliceapp-57", "Role": "READER" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "${zone}-aliceapp-57", "Role": "WRITER" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Experiments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Availability @ AWS ALB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1 - ($FAILED_TARGET + $FAILED_ELB) / $TOTAL",
     "type": "math"
    }
   ]
  },
  {
   "title": "Latency @ K8s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{exported_service=\"prod-alice-web-http@kubernetes\"}[$__rate_interval])) /\r\nsum(increase(traefik_service_request_duration_seconds_count{exported_service=\"prod-alice-web-http@kubernetes\"}[$__rate_interval]))",
     "legendFormat": "__auto",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "com.mysql.jdbc.exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:prod AND priority:ERROR AND (role:\"web\" OR role:\"jobs\") AND message:com.mysql.jdbc.exceptions.*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Throughput @ K8s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=\"${zone}-alice-web-http@kubernetes\"}[1m])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row was updated or deleted by another transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:prod AND \"Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.alice.HotelUser#\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "org.hibernate.exception",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:prod AND priority:ERROR AND (role:\"web\" OR role:\"jobs\") AND message:org.hibernate.exception.*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC Throughput PROD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "min by(job)(100 - (sum by (job, instance)(increase(jvm_gc_collection_seconds_sum[1m])) * 100 / sum by (job, instance) (increase(process_cpu_seconds_total[1m]))))"
    }
   ]
  },
  {
   "title": "G1 Old Generation PROD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{container=\"aliceapp\", gc=\"G1 Old Generation\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC count PROD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "max (rate(jvm_gc_collection_seconds_count[1m])) by (job, gc)",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}