{
 "title": "ALICE Monolith - API",
 "tags": [
  "alice",
  "monolith",
  "api",
  "alice-web"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "zone", "label": "Zone", "query": "prod,ent1" }
  ]
 },
 "panels": [
  { "title": "Quick facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput @ K8s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=\"${zone}-alice-web-http@kubernetes\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures @ K8s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{exported_service=\"prod-alice-web-http@kubernetes\", code=~\"5[0-9][0-9]\"}[$__rate_interval]))\r\n/\r\nsum(rate(traefik_service_requests_total{exported_service=\"prod-alice-web-http@kubernetes\"}[$__rate_interval])) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency @ AWS ALB",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/prod-us-east-1-public-ingress/1efa7e7244eb4fbd"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Open Connections @ K8s",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(traefik_service_open_connections{target_namespace=\"${zone}\", target_service=\"alice-web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (kube_deployment_status_replicas_ready{deployment=\"alice-web\", namespace=\"$zone\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment) (kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"alice-web\", namespace=\"$zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB CPU %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "prod-aliceapp-d5699fc1", "Role": "WRITER" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB-Reader CPU %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "prod-aliceapp-d5699fc1", "Role": "READER" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Potential problems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    { "title": "Deep dive", "type": "dashlist", "gridPos": { "h": 16, "w": 8, "x": 0, "y": 360 } },
    {
     "title": "Ingress 404 issue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 360 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "role",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:${zone} AND (role:\"alice-staff-backend\") AND (message:\"404 Not Found\" AND message:\"prod-web-internal.aliceapp.com\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Elastic Search Result Window Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 360 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "role",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:${zone} AND (role:web OR role:jobs) AND message:\"Result Window\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Error initializing Grails",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 512 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "role",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:${zone} AND (role:\"web\" OR role:\"jobs\") AND message:\"Error initializing Grails\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Invalidating cached JSON for Hotel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 512 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "role",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:${zone} AND (role:\"web\" OR role:\"jobs\") AND message:\"Invalidating cached JSON for Hotel\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "JGroups DB Issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 520 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "\"java.sql.SQLException: Access denied for user\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Balancer (alice-web + BFF, as they share ALB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/prod-us-east-1-public-ingress/1efa7e7244eb4fbd"
     },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $D", "type": "math" },
    { "expression": "$B / $D", "type": "math" },
    { "expression": "$C / $D", "type": "math" }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/prod-us-east-1-public-ingress/1efa7e7244eb4fbd"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=\"${zone}-alice-web-http@kubernetes\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{exported_service=\"prod-alice-web-http@kubernetes\"}[$__rate_interval])) /\r\nsum(increase(traefik_service_request_duration_seconds_count{exported_service=\"prod-alice-web-http@kubernetes\"}[$__rate_interval]))",
     "legendFormat": "AVG"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{target_namespace=\"prod\", target_service=\"alice-web\"}[$__rate_interval])))",
     "legendFormat": "p75",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{target_namespace=\"prod\",target_service=\"alice-web\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket{target_namespace=\"prod\",target_service=\"alice-web\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_ready{deployment=\"alice-web\", namespace=\"prod\"})",
     "legendFormat": "Up & Running"
    },
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas{deployment=\"alice-web\", namespace=\"prod\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Open Connections @ K8s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(traefik_service_open_connections{target_namespace=\"${zone}\", target_service=\"alice-web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lock wait timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:\"web\" AND message:\"com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "App 5XX @ AWS ALB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/prod-web-alb/b5b23ee3797ecde8"
     },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "priority",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:web",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DB Connection Pool exhausted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:\"web\" AND priority:ERROR AND message:\"org.apache.tomcat.jdbc.pool.PoolExhaustedException\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs, WARN+ERROR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "priority",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:web AND (priority:ERROR OR priority:WARN)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Too many connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND priority:ERROR AND role:\"web\" AND message:\"Too many connections\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Elastic Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "zone",
   "collapsed": true,
   "panels": [
    {
     "title": "Data Nodes",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod", "NodeId": "*" },
       "metricName": "SearchLatency",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Maximum"
      },
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod", "NodeId": "*" },
       "metricName": "SearchRate",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Average"
      },
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod", "NodeId": "*" },
       "metricName": "IndexingRate",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Documents",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
       "metricName": "DeletedDocuments",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Maximum"
      },
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
       "metricName": "SearchableDocuments",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Data Nodes - CPU usage (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Master Nodes - CPU usage (trimmed mean)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod", "NodeId": "*" },
       "metricName": "MasterCPUUtilization",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "IQM"
      }
     ]
    },
    {
     "title": "Search - Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
       "metricName": "SearchRate",
       "namespace": "AWS/ES",
       "period": "1m",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Search - Duration, p100",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
       "metricName": "SearchLatency",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Indexing - Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
       "metricName": "IndexingRate",
       "namespace": "AWS/ES",
       "period": "1m",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Indexing - Duration, p100",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "ClientId": "763386454006", "DomainName": "alice-prod" },
       "metricName": "IndexingLatency",
       "namespace": "AWS/ES",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "sql": {
        "from": { "property": { "name": "AWS/ES", "type": "string" }, "type": "property" },
        "select": {
         "name": "MIN",
         "parameters": [
          { "name": "SearchRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "alice-prod" }, "property": { "name": "DomainName", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT MIN(SearchRate) FROM \"AWS/ES\" WHERE DomainName = 'alice-prod'",
       "statistic": "Maximum"
      }
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "WRITER DB CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "prod-aliceapp-d5699fc1", "Role": "WRITER" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "READER DB CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "prod-aliceapp-d5699fc1", "Role": "READER" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "prod-aliceapp-d5699fc1", "Role": "WRITER" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Experiments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability @ AWS ALB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 788 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expression": "1 - ($FAILED_TARGET + $FAILED_ELB) / $TOTAL",
       "type": "math"
      }
     ]
    },
    {
     "title": "Row was updated or deleted by another transaction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 788 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:prod AND \"Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.alice.HotelUser#\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "com.mysql.jdbc.exceptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 788 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:prod AND priority:ERROR AND (role:\"web\" OR role:\"jobs\") AND message:com.mysql.jdbc.exceptions.*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "GC Throughput PROD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 796 },
     "targets": [
      {
       "expr": "min by(job)(100 - (sum by (job, instance)(increase(jvm_gc_collection_seconds_sum[1m])) * 100 / sum by (job, instance) (increase(process_cpu_seconds_total[1m]))))"
      }
     ]
    },
    {
     "title": "G1 Old Generation PROD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 796 },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{container=\"aliceapp\", gc=\"G1 Old Generation\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "org.hibernate.exception",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 796 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:prod AND priority:ERROR AND (role:\"web\" OR role:\"jobs\") AND message:org.hibernate.exception.*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "GC count PROD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 804 },
     "targets": [
      {
       "expr": "max (rate(jvm_gc_collection_seconds_count[1m])) by (job, gc)",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}