{
 "title": "controlsData all endpoints",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "control",
    "label": "Control",
    "query": {
     "query": "label_values(controlsData_response_timer_seconds_sum, control)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(controlsData_response_timer_seconds_sum, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 20 slowest endpoints for past 24h (calculated by average response time)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, avg by(usecase, control) (quantile_over_time(0.95, controlsData_response_timer_seconds_max{namespace=\"$namespace\"}[24h])))",
     "legendFormat": "{{control}} ({{usecase}})"
    }
   ]
  },
  {
   "title": "Response time for selected controls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(control) (increase(controlsData_response_flow_duration_seconds_sum{namespace=\"$namespace\", control=~\"$control\"}[$__rate_interval])) /\r\nsum by(control) (increase(controlsData_response_flow_duration_seconds_count{namespace=\"$namespace\", control=~\"$control\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput for selected controls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (control) (increase(controlsData_response_timer_seconds_count{namespace=\"$namespace\", control=~\"$control\"}[$__rate_interval]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stats for $control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "control" },
  {
   "title": "Proxy response status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(responseStatus) (rate(controlsData_proxyResponseStatus_total{control=\"$control\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time for $control (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "max by(usecase) (increase(controlsData_response_flow_duration_seconds_sum{control=\"$control\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput for $control",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(increase(controlsData_response_timer_seconds_count{control=\"$control\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "${control}"
    }
   ]
  }
 ]
}