{
 "title": "Job Runner Status",
 "time": { "from": "2024-05-10T15:07:24.422Z", "to": "2024-05-10T16:03:50.002Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Size of Server Worker Pool",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobrunr_background_job_server_worker_pool_size_total{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "jobrunr_jobs_processing{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg System CPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobrunr_background_job_server_process_cpu_load{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "jobrunr_background_job_server_process_all_located_memory{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jobrunr_background_job_server_system_total_memory",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobrunr_background_job_server_first_heartbeat{container=\"hskp-service\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "jobrunr_background_job_server_last_heartbeat{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "expr": "jobrunr_background_job_server_process_free_memory{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jobrunr_background_job_server_system_free_memory{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Real Time Graph",
   "type": "timeseries",
   "description": "Jobs Succeeded and Failed",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "jobrunr_jobs_failed{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jobrunr_jobs_succeeded{container=\"hskp-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}