{
 "title": "PMS Integrations",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "rest-proxy,rest-proxy-int" }
  ]
 },
 "panels": [
  { "title": "Quick facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "rest-proxy-int, req/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=\"prod-rest-proxy-int-http@kubernetes\"}[1m])) / 60"
    }
   ]
  },
  {
   "title": "rest-proxy-int, Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{exported_service=\"prod-rest-proxy-int-http@kubernetes\", code!~\"2[0-9][0-9]\"}[$__rate_interval]))\r\n/\r\nsum(rate(traefik_service_requests_total{exported_service=\"prod-rest-proxy-int-http@kubernetes\"}[$__rate_interval])) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rest-proxy-int, Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{exported_service=\"prod-rest-proxy-int-http@kubernetes\"}[$__rate_interval])) /\r\nsum(increase(traefik_service_request_duration_seconds_count{exported_service=\"prod-rest-proxy-int-http@kubernetes\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "rest-proxy-int, Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"rest-proxy-int\", namespace=\"prod\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Open API, req/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=\"prod-rest-proxy-http@kubernetes\"}[1m])) / 60"
    }
   ]
  },
  {
   "title": "Open API, Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{exported_service=\"prod-rest-proxy-http@kubernetes\", code!~\"2[0-9][0-9]\"}[$__rate_interval]))\r\n/\r\nsum(rate(traefik_service_requests_total{exported_service=\"prod-rest-proxy-http@kubernetes\"}[$__rate_interval])) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open API, Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{exported_service=\"prod-rest-proxy-http@kubernetes\"}[$__rate_interval])) /\r\nsum(increase(traefik_service_request_duration_seconds_count{exported_service=\"prod-rest-proxy-http@kubernetes\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Open API, Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"rest-proxy\", namespace=\"prod\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Triage - ${service}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "service",
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{exported_service=\"prod-${service}-http@kubernetes\"}[1m])) / 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_request_duration_seconds_sum{exported_service=\"prod-${service}-http@kubernetes\"}[$__rate_interval])) /\r\nsum(increase(traefik_service_request_duration_seconds_count{exported_service=\"prod-${service}-http@kubernetes\"}[$__rate_interval]))",
       "legendFormat": "__auto",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Failures (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{exported_service=\"prod-${service}-http@kubernetes\", code!~\"2[0-9][0-9]\"}[$__rate_interval]))\r\n/\r\nsum(rate(traefik_service_requests_total{exported_service=\"prod-${service}-http@kubernetes\"}[$__rate_interval])) \r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failures by response code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(code) (rate(traefik_service_requests_total{exported_service=\"prod-${service}-http@kubernetes\", code!~\"2[0-9][0-9]\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs, ERROR",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment:prod AND role:\"${service}\" AND priority:ERROR",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Logs, ERROR stream",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment:prod AND role:\"${service}\" AND priority:ERROR",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}