{
 "title": "Ticket Automation",
 "tags": [ "alice" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "zone", "label": "Zone", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "Sub-tickets count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:\"jobs\" AND message:\"FOH-17491: Creating child ticket for service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Potential problems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Logs, ERROR",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:prod AND service_name:alice-jobs AND priority:ERROR AND (logger:com.alice.ticket.automation.TicketAutomationService OR logger:com.alice.ticket.automation.TicketAutomationSqsEventReaderService)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs stream, ERROR",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "environment:prod AND role:jobs AND priority:ERROR AND (logger:com.alice.ticket.automation.TicketAutomationService OR logger:com.alice.ticket.automation.TicketAutomationSqsEventReaderService)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Sub-ticket creation errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:\"jobs\" AND message:\"FOH-17491: Error creating child ticket for service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event processing errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:\"jobs\" AND message:\"FOH-15703: Error occurred while processing messages for\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Skipped events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "environment:${zone} AND role:\"jobs\" AND message:\"FOH-17491: skipping event type\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "SQS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Unprocessed ticket events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "prod-aliceapp-ticket-automation-events.fifo"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Unprocessed ticket events age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "prod-aliceapp-ticket-automation-events.fifo"
     },
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Dead-letter queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "prod-aliceapp-ticket-automation-events-dead-letter.fifo"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}