{
 "title": "Pod Stats & Info",
 "description": "This is for insight on important Kubernetes app metrics.\r\nWhat recources is a Pod actually using and what are it's limits or requests and what part is each container consuming?\r\nAlso has graphs for networking, disks, restarts docker images etc",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod_ip",
    "label": "Pod IP",
    "query": "label_values(kube_pod_info{namespace=~\"^$namespace$\", pod=~\"^$pod$\"}, pod_ip)"
   },
   {
    "name": "phase",
    "label": "Phase",
    "query": "label_values(kube_pod_status_phase{namespace=~\"^$namespace$\", pod=~\"^$pod$\"}, phase)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "kubernetes.pod.name: $pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": {
    "content": "<h1><center>$phase</center></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 10 },
   "options": {
    "content": "<h1><center>$container</center></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "IP",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 10 },
   "options": {
    "content": "<h1><center>$pod_ip</center></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "CPU: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\"}[1m]))",
     "legendFormat": "CPU: $pod"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"^$namespace$\", pod=~\"^$pod$\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "CPU: $container",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\",container=\"$container\",resource=\"cpu\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\",container=\"$container\",resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\",container=\"$container\"}[1m])) by (container)",
     "legendFormat": "Usage: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\"})",
     "legendFormat": "MEM"
    },
    {}
   ]
  },
  {
   "title": "Memory: $container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "repeat": "container",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\",resource=\"memory\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\",resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\",container=\"$container\"}) by (container)",
     "legendFormat": "Usage: {{ container }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Network-Errors: $pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Receive-Errors%"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Receive-Dropped%"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Transmit-Errors%"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Transmit-Dropped%"
    }
   ]
  }
 ]
}